name: Time Check

on: workflow_dispatch

jobs:
  check-time:
    runs-on: ubuntu-latest
    steps:
      - name: Check current minute
        run: |
          echo "Current time: $(date)"
          MINUTE=$(date +'%M')
          if [[ "$MINUTE" -ge 50 ]] || [[ "$MINUTE" -le 4 ]]; then
            echo "This workflow can only be executed between 05 and 49 minutes of each hour."
            exit 1
          fi
      - name: Next step
        run: |
          echo "Next step start ..."
          